import type { Plugin } from "@opencode-ai/plugin"
import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"

// Python guardrails for uv-managed projects.
//
//   tool.execute.before (bash) → blocks `pip install`, bare `python …`, etc.,
//     but only when $directory/uv.lock exists.
//   tool.execute.after  (write|edit) → runs `uvx ruff check --fix` + `uvx ruff format`
//     on .py files, but only when [tool.ruff] / ruff.toml is configured.
//
// Mirrors the Claude Code hooks in ~/.claude/hooks/. Escape hatch:
// `.claude/no-python-hooks` at project root short-circuits everything.

const BLOCK_PATTERNS: Array<[RegExp, string, string]> = [
  [/(?:^|\s)pip3?\s+install\b/, "pip install", "uv add"],
  [/(?:^|\s)pip3?\s+uninstall\b/, "pip uninstall", "uv remove"],
  [/(?:^|\s)python3?\s+-m\s+pip\b/, "python -m pip", "uv add / uv remove"],
  [/(?:^|\s)python3?\s+-m\s+pytest\b/, "python -m pytest", "uv run pytest"],
]

const BARE_TOOLS = ["pip", "pip3", "python", "python3", "pytest", "ruff"]

// Match a bare tool at start-of-command, after &&, ||, ;, |, or following
// whitespace. Tool must be followed by whitespace or end-of-string.
function matchesBareTool(tool: string, cmd: string): boolean {
  const re = new RegExp(`(^|&&|\\|\\||;|\\|)\\s*${tool}(\\s|$)`)
  return re.test(cmd)
}

// Proto fast-path — universal convention, silent skip.
const PROTO_PATTERNS = [/_pb2\.pyi?$/, /_pb2_grpc\.py$/]

// Generated-file marker in file header — case-insensitive, first 30 lines.
const GENERATED_MARKER = /@generated|DO NOT EDIT|Generated by|autogenerated/i

function hasMarker(dir: string, marker: string): boolean {
  return existsSync(join(dir, marker))
}

function hasRuffConfig(dir: string): boolean {
  if (hasMarker(dir, "ruff.toml") || hasMarker(dir, ".ruff.toml")) return true
  const pyproject = join(dir, "pyproject.toml")
  if (!existsSync(pyproject)) return false
  try {
    return /^\[tool\.ruff/m.test(readFileSync(pyproject, "utf8"))
  } catch {
    return false
  }
}

function generatedMarker(filePath: string): string | null {
  try {
    const head = readFileSync(filePath, "utf8").split("\n", 30).join("\n")
    const m = head.match(GENERATED_MARKER)
    return m ? m[0] : null
  } catch {
    return null
  }
}

export const PythonHooksPlugin: Plugin = async ({ directory, $ }) => {
  return {
    "tool.execute.before": async (input, output) => {
      const tool = String(input?.tool ?? "").toLowerCase()
      if (tool !== "bash" && tool !== "shell") return
      if (hasMarker(directory, ".claude/no-python-hooks")) return
      if (!hasMarker(directory, "uv.lock")) return

      const args = output?.args as Record<string, unknown> | undefined
      const command = typeof args?.command === "string" ? args.command : ""
      if (!command) return

      // Allow anything explicitly under uv / uvx / uv run.
      if (/^\s*(uv |uvx |uv run )/.test(command)) return

      for (const [re, what, replacement] of BLOCK_PATTERNS) {
        if (re.test(command)) {
          throw new Error(
            `[python-hooks] Blocked '${what}' — use '${replacement}' instead.`,
          )
        }
      }
      for (const tool of BARE_TOOLS) {
        if (matchesBareTool(tool, command)) {
          const replacement = tool === "ruff" ? "uvx ruff" : `uv run ${tool}`
          throw new Error(
            `[python-hooks] Blocked bare '${tool}' — use '${replacement}'.`,
          )
        }
      }
    },

    "tool.execute.after": async (input) => {
      const tool = String(input?.tool ?? "").toLowerCase()
      if (tool !== "write" && tool !== "edit") return
      if (hasMarker(directory, ".claude/no-python-hooks")) return
      if (!hasRuffConfig(directory)) return

      const args = input?.args as Record<string, unknown> | undefined
      const filePath =
        (typeof args?.filePath === "string" && args.filePath) ||
        (typeof args?.file_path === "string" && args.file_path) ||
        ""
      if (!filePath || !filePath.endsWith(".py")) return

      // 1. Proto fast-path — silent skip.
      if (PROTO_PATTERNS.some((re) => re.test(filePath))) return

      // 2. Header marker — skip + log hint.
      const marker = generatedMarker(filePath)
      if (marker) {
        console.warn(
          `[python-hooks] skipped ruff on ${filePath} — header matched "${marker}" (looks generated)`,
        )
        return
      }

      // 3. Defer to ruff's own exclude config via --force-exclude.
      try {
        await $`uvx ruff check --fix --force-exclude --quiet ${filePath}`
          .quiet()
          .nothrow()
      } catch {
        // non-fatal
      }
      try {
        await $`uvx ruff format --force-exclude --quiet ${filePath}`
          .quiet()
          .nothrow()
      } catch {
        // non-fatal
      }
    },
  }
}
