#!/usr/bin/env bash
# PostToolUse:Write|Edit — run ruff fix + format on the touched Python file.
#
# Fires only when:
#   - the file path ends in .py
#   - the file exists on disk
#   - the project has opted into ruff: [tool.ruff] in $CLAUDE_PROJECT_DIR/pyproject.toml
#     OR a ruff.toml / .ruff.toml at $CLAUDE_PROJECT_DIR root
#   - .claude/no-python-hooks is absent
#
# Generated-file handling (in order):
#   1. Proto fast-path (*_pb2.py / *_pb2_grpc.py / *_pb2.pyi): silent skip
#   2. Header peek for "@generated", "DO NOT EDIT", "Generated by",
#      "autogenerated" in the first 30 lines: skip + emit one-line stderr hint
#   3. Otherwise, invoke ruff with --force-exclude, which makes ruff honor the
#      project's own [tool.ruff] extend-exclude even though we pass an explicit
#      file path. Project's exclude config is the source of truth for
#      "non-proto generated stuff" — we don't try to guess.
#
# Uses `uvx ruff` so it works regardless of whether the project lists ruff as a
# dep. Ruff itself walks up from the file's dir to find the nearest pyproject /
# ruff.toml, so per-subproject configs in a monorepo are respected.
#
# Always exits 0. We never block the edit; formatting failures are non-fatal.

set -uo pipefail

project_dir="${CLAUDE_PROJECT_DIR:-$PWD}"

[[ -f "$project_dir/.claude/no-python-hooks" ]] && exit 0

has_ruff_config() {
  [[ -f "$project_dir/ruff.toml" ]] && return 0
  [[ -f "$project_dir/.ruff.toml" ]] && return 0
  [[ -f "$project_dir/pyproject.toml" ]] && grep -q '^\[tool\.ruff' "$project_dir/pyproject.toml" && return 0
  return 1
}
has_ruff_config || exit 0

input="$(cat)"
# NotebookEdit uses notebook_path; Write/Edit use file_path.
file_path="$(printf '%s' "$input" | jq -r '.tool_input.file_path // .tool_input.notebook_path // ""')"

[[ -z "$file_path" ]] && exit 0
[[ "$file_path" == *.py || "$file_path" == *.ipynb ]] || exit 0
[[ -f "$file_path" ]] || exit 0

# 1. Proto fast-path — silent skip. Universal convention, .py only.
case "$file_path" in
  *_pb2.py|*_pb2_grpc.py|*_pb2.pyi) exit 0 ;;
esac

# 2. Header peek — generated marker in the first 30 lines.
marker_re='@generated|DO NOT EDIT|Generated by|autogenerated'
matched="$(head -n 30 "$file_path" 2>/dev/null | grep -oEi "$marker_re" | head -n 1 || true)"
if [[ -n "$matched" ]]; then
  printf 'note: skipped ruff on %s — header matched "%s" (looks generated)\n' "$file_path" "$matched" >&2
  exit 0
fi

# 3. Defer to ruff's own exclude config via --force-exclude.
command -v uvx >/dev/null 2>&1 || exit 0

uvx ruff check --fix --force-exclude --quiet "$file_path" >/dev/null 2>&1 || true
uvx ruff format --force-exclude --quiet "$file_path"      >/dev/null 2>&1 || true

exit 0
